### PR TITLE
not writeable on Jetstream

### PR DESCRIPTION
**Pull request by davhunt**

### CODE REVIEW

**Comment by soichih** [comment]
@davhunt Can you explain why we need to set this? 
`SINGULARITY_DISABLE_CACHE=True`

**Comment by davhunt** [comment]
@soichih It's a suggestion from here https://neurostars.org/t/filenotfounderror-errno-2-no-such-file-or-directory-home-fmriprep-cache/3770 but another error just came up

**Comment by davhunt** [comment]
I think with slurm, it doesn't bind the present working directory to the container somehow.  So when it searches for the fs-license for example it doesn't see .license anywhere for example.

I was trying to follow this https://fmriprep.readthedocs.io/en/latest/singularity.html#running-singularity-on-a-slurm-system but no luck,

**Comment by soichih** [comment]
We don't run freesurfer inside fmriprep so you shouldn't have to worry about the freesurfer license. We run freesurfer outside fmriprep and pass in the freesurfer output to fmriprep. Is fmriprep not detecting our freesurfer input maybe?

**Pull request merged**
